name: Run Django Tests with Docker Compose

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Run Docker Compose
      working-directory: ${{ github.workspace }}  # Establecer el directorio de trabajo como la raíz del repo
      run: |
        docker-compose up --build -d  # Levantar contenedores en segundo plano

    - name: Wait for DB to be ready
      run: |
        docker-compose exec -T db bash -c "until pg_isready -h db -U postgres; do sleep 1; done"  # -T para evitar TTY error

    - name: Run Migrations and Tests
      run: |
        docker-compose exec -T web python manage.py migrate  # -T para evitar TTY error
        docker-compose exec -T web python manage.py test --noinput  # -T para evitar TTY error

    - name: Tear down Docker Compose
      if: always()
      run: |
        docker-compose down
