name: Run Django Tests with Docker Compose

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_NAME: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_HOST: db
      ADMIN_USER: admin_user
      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: secure_password

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Run Docker Compose
      working-directory: ${{ github.workspace }}  # Establecer el directorio de trabajo como la raíz del repo
      run: |
        docker-compose up --build -d  # Levantar contenedores en segundo plano

    - name: Wait for DB to be ready
      run: |
        docker-compose exec -T db bash -c "until pg_isready -h db -U django_user; do sleep 1; done"  # -T para evitar TTY error

    - name: Wait for MySQL to initialize
      run: sleep 15 # Adding a delay

    - name: Run Tests
      run: |
        echo "Running tests..."
        docker-compose exec -T web bash -c "cd /backend && python manage.py test --noinput" || docker-compose logs web  # Navegar a /backend para ejecutar manage.py

    - name: Tear down Docker Compose
      if: always()
      run: |
        docker-compose down
